
//
//  RecipeSteps.swift
//  Davids Grindz
//
//  Created by Steven Lipton on 3/23/25.
//
//  Use this code as a model for the linkedIN Learning course Complete Guide to SwiftUI


import Foundation
/// A single record in the `collection of recipe steps`
/// - parameter recipeID : **First half of Primary key**,  identifies the recipe
/// - parameter rowID : **Second half of Primary key**, identifies the row in the recipe
/// - parameter itemCode : The `id` of the ingredient used
/// - parameter quantity : The amount required for this step
/// - parameter actions : An instruction for this step. May be a comment for an ingredient.
/// - parameter isAction : A flag to determine if stp is an instruction(`true`) or ingredient(`false`).
struct RecipeStep:Identifiable,Hashable,Equatable{
    var recipeID:Int = -1 //Key 1st half
    var rowID:Int = 0     //Key 2nd half
    var itemCode:Int = 0   //
    var quantity:Double = 0.0
    var actions:String
    var isAction:Bool = false
    
    /// **Primary Key** A unique ID for search operations, combining `recipeID` and `rowID`.
    var id:Int{recipeID * 1000 + rowID}
    
    /// A blank `RecipeStep` to use when initializing variables.
    static var blank:RecipeStep{RecipeStep(actions:"")}
}

@Observable
class RecipeSteps{
    
    var table:[RecipeStep] = []
    
    init(){
        preload()
    }

//----- Add Methods
    
    /// Find the next ID available for a recipe row
    /// - Returns one greater than the largest ID
    func nextRowID(recipeID:Int)->Int{
        let steps = allSteps(for: recipeID)
        if let lastStep = steps.max(by: {$0.rowID < $1.rowID}){
            return lastStep.rowID + 1
        } else {
            return 0
        }
    }
    
    /// Add the row with a `RecipeStep`
    func addRow(recipeStep:RecipeStep){
        var recipeStep = recipeStep                      //make mutable copy
        recipeStep.rowID = nextRowID(recipeID: recipeStep.recipeID) //assign the correct row ID
        table.append(recipeStep)                        // Append the row
    }
    
    /// Add the row specifying properties.
    /// - if `rowID` is `nil` or omitted, will generate a `rowID`
    func addRow(recipeID:Int,rowID:Int! = nil,itemCode:Int,quantity:Double,actions:String,isAction:Bool){
        print("in row!")
        // create a new mutable row from the arguments, if row is nil set to 0
        var newRow:RecipeStep = RecipeStep(recipeID: recipeID, rowID: rowID ?? 0, itemCode: itemCode, quantity: quantity, actions: actions,isAction: isAction)
        print(newRow)
        //find the correct row ID for this.
        // nil row indicates making a new row
        if let rowID = rowID{ //explicit row creation. if row exists add to end.
            if rowExists(for:recipeID,row:rowID){
                // row exists, so replace the row and return
                updateRow(recipeStep:newRow)
                return
            }else{
                // row does not exist(i.e. out of bounds) -- set `rowID` to append the row
                newRow.rowID = nextRowID(recipeID: recipeID)
            }
        } else {
            // New row, so append the row.
            newRow.rowID = nextRowID(recipeID: recipeID)
        }
        //append the row.
        table.append(newRow)
    }
    
 //----- Delete Methods
    ///Delete based on an `id`
    func removeRow(rowID:Int){
        // find the index of the item with id, and remove from that index.
        if let index = table.firstIndex(where: {$0.id == rowID}){
            table.remove(at: index)
        }
    }
    /// Cleans up aftere deletion of a recipe to prevent orphan entries
    func removeRecipeSteps(for recipeID:Int){
        table.removeAll(where: {$0.recipeID == recipeID})
    }
    
    
//----- Update methods
    
    /// Update based on a `recipeStep`
    func updateRow(recipeStep:RecipeStep){
        //find the index of that id, and replace the element at that index.
        if let index = table.firstIndex(where: {$0.id == recipeStep.id}){
            print("Index is",index)
            print(recipeStep)
            table[index] = recipeStep
        }
    }
    
//----- Insert methods
    ///Inserts a row after a specified row, updating the `rowID` property to keep in sequence
    /// - parameter after: a selected  `RecipeStep` to place a new row after. also specifies the recipe involoved.
    /// - parameter with: a new `RecipeStep` to insert. `RecipeID` and `RowID` are generated by this method, and are therefore not siginifant in the argument.
    func insertRow(after baseRow:RecipeStep,with insertedRow:RecipeStep){
        // if the base row exists
        if let baseIndex = table.firstIndex(where: {$0.recipeID == baseRow.recipeID && $0.rowID == baseRow.rowID }){
                // Make space for the new row in the `rowIDs`
                for index in table.startIndex..<table.endIndex{
                    if table[index].recipeID == baseRow.recipeID && table[index].rowID > baseRow.rowID{
                        table[index].rowID += 1
                    }
                }
                // make a mutable row, and change the keys for insertion
                var newRow = insertedRow
                newRow.recipeID = baseRow.recipeID
                newRow.rowID = baseRow.rowID + 1
                // do the insertion
                let newIndex = baseIndex + 1
                table.insert(newRow, at: newIndex)
            } else {
                print("No changes made")
            }
        }
    
    
//----- Find methods
    
    ///Return an step by its `id`
    func step(id:Int)->RecipeStep!{
        table.first{$0.id == id}
    }
    
    //return the index of a row
        func findRowIndex(id:Int)->Int!{
            table.firstIndex{$0.id == id}
        }
    
    ///Return an step by its `recipeID` and `row`
    func step(recipeID:Int,row:Int)->RecipeStep!{
        table.first{$0.recipeID == recipeID && $0.rowID == row}
    }
    
    ///Find all steps by `recipeID`
    func allSteps(for recipeID:Int )->[RecipeStep]{
        table.filter{$0.recipeID == recipeID}
    }
    ///Find all ingredient steps
    func ingredientSteps(for recipeID:Int )->[RecipeStep]{
        table.filter{$0.recipeID == recipeID && !$0.isAction}
    }
    /// Find all action steps
    func actionSteps(for recipeID:Int )->[RecipeStep]{
        table.filter{$0.recipeID == recipeID && $0.isAction}
    }
    
    /// Find if a row exists
    func rowExists(for recipeID:Int, row:Int)->Bool{
        table.contains(where:{$0.recipeID == recipeID && $0.rowID == row})
    }
    
//---- Error checking
    /// find if there are duplicate records
    /// - returns an array of `ids` indiciating the recipe and row duplicated.
    func duplicateIDs()->[Int]{
        let testArray = table.map{$0.id}.sorted()
        var duplicateIDs:[Int] = []
        for id in testArray{
            let idCount = testArray.filter{$0 == id}.count
            if idCount > 1 {
                duplicateIDs.append(id)
            }
        }
        return duplicateIDs
    }
    
    
    /// preloads data into the app
    ///note I could have done this other ways, but for simplicity, I just added them to the array.
    func preload(){ table += [
        RecipeStep(recipeID: 01, rowID: 0, itemCode: 4, quantity: 4, actions: ""),
        RecipeStep(recipeID: 01, rowID: 1, itemCode: 3, quantity: 7, actions: ""),
        RecipeStep(recipeID: 01, rowID: 2, itemCode: 2, quantity: 0.120, actions: "water at 90ºF/32ºC"),
        RecipeStep(recipeID: 01, rowID: 3, itemCode: 0, quantity: 0.0, actions: "Mix water, yeast and sugar",isAction:true),
        RecipeStep(recipeID: 01, rowID: 4, itemCode: 0, quantity: 0, actions: "Let stand 3 to 5 minutes",isAction:true),
        RecipeStep(recipeID: 01, rowID: 5, itemCode: 1, quantity: 360, actions: ""),
        RecipeStep(recipeID: 01, rowID: 6, itemCode: 4, quantity: 4, actions: ""),
        RecipeStep(recipeID: 01, rowID: 7, itemCode: 5, quantity: 19, actions: ""),
        RecipeStep(recipeID: 01, rowID: 8, itemCode: 6, quantity: 6, actions: ""),
        RecipeStep(recipeID: 01, rowID: 9, itemCode: 0, quantity: 0, actions: "Combine in mixer with dough hook",isAction:true),
        RecipeStep(recipeID: 01, rowID: 10, itemCode: 7, quantity: 30, actions: ""),
        RecipeStep(recipeID: 01, rowID: 11, itemCode: 0, quantity: 0, actions: "Mix Oil, dry and wet ingredients",isAction:true),
        RecipeStep(recipeID: 01, rowID: 12, itemCode: 0, quantity: 0, actions: "Knead dough 5 to 7 minutes once combined",isAction:true),
        RecipeStep(recipeID: 01, rowID: 13, itemCode: 0, quantity: 0, actions: "Place in oiled containers",isAction:true),
        RecipeStep(recipeID: 01, rowID: 14, itemCode: 0, quantity: 0, actions: "Store in refrigerator minimum four hours",isAction:true),
        RecipeStep(recipeID: 02, rowID: 0, itemCode: 2, quantity: 0.590, actions: ""),
        RecipeStep(recipeID: 02, rowID: 1, itemCode: 3, quantity: 2, actions: ""),
        RecipeStep(recipeID: 02, rowID: 2, itemCode: 0, quantity: 0, actions: "Mix yeast and water in mixer with dough hook on slow speed for 2-3 minutes until yeast is dissolved",isAction:true),
        RecipeStep(recipeID: 02, rowID: 3, itemCode: 1, quantity: 1000, actions: ""),
        RecipeStep(recipeID: 02, rowID: 4, itemCode: 0, quantity: 0, actions: "Mix in flour slowly until completely comined and no dry bits left",isAction:true),
        RecipeStep(recipeID: 02, rowID: 5, itemCode: 0, quantity: 0, actions: "Let dough rest 2 minutes",isAction:true),
        RecipeStep(recipeID: 02, rowID: 6, itemCode: 2, quantity: 0.010, actions: ""),
        RecipeStep(recipeID: 02, rowID: 7, itemCode: 6, quantity: 30, actions: ""),
        RecipeStep(recipeID: 02, rowID: 8, itemCode: 0, quantity: 0, actions: "Add water and salt to dough until completely combined",isAction:true),
        RecipeStep(recipeID: 02, rowID: 9, itemCode: 0, quantity: 0, actions: "Allow dough to rest for 5 minutes",isAction:true),
        RecipeStep(recipeID: 02, rowID: 10, itemCode: 0, quantity: 0, actions: "Place dough into very well oiled fermenting tray. Store covered at room temperature 3-4 hours",isAction:true),
        RecipeStep(recipeID: 02, rowID: 11, itemCode: 0, quantity: 0, actions: "Cut dough into six 260g dough balls",isAction:true),
        RecipeStep(recipeID: 02, rowID: 12, itemCode: 0, quantity: 0, actions: "Place in fermenting tray. Store covered 30 minutes to 1 hour at room temperature",isAction:true),
        RecipeStep(recipeID: 02, rowID: 13, itemCode: 0, quantity: 0, actions: "Ferment in refrigerator 24-48 hours",isAction:true),
        RecipeStep(recipeID: 03, rowID: 00, itemCode: 38, quantity: 260, actions: ""),
        RecipeStep(recipeID: 03, rowID: 01, itemCode: 0, quantity: 0, actions: "Warm to room temperature before service",isAction:true),
        RecipeStep(recipeID: 03, rowID: 02, itemCode: 0, quantity: 590, actions: "From one dogh ball press out to 25cm",isAction:true),
        RecipeStep(recipeID: 03, rowID: 03, itemCode: 12, quantity: 120, actions: ""),
        RecipeStep(recipeID: 03, rowID: 04, itemCode: 0, quantity: 0, actions: "Spread Pizza sauce evenly",isAction:true),
        RecipeStep(recipeID: 03, rowID: 05, itemCode: 21, quantity: 100, actions: ""),
        RecipeStep(recipeID: 03, rowID: 06, itemCode: 0, quantity: 0, actions: "Spread cheese over sauce",isAction:true),
        RecipeStep(recipeID: 03, rowID: 07, itemCode: 9, quantity: 30, actions: "Sliced segements",isAction:true),
        RecipeStep(recipeID: 03, rowID: 08, itemCode: 8, quantity: 60, actions: ""),
        RecipeStep(recipeID: 03, rowID: 09, itemCode: 10, quantity: 20, actions: ""),
        RecipeStep(recipeID: 03, rowID: 10, itemCode: 11, quantity: 20, actions: ""),
        RecipeStep(recipeID: 03, rowID: 11, itemCode: 0, quantity: 0, actions: "Add other ingredients to top",isAction:true),
        RecipeStep(recipeID: 03, rowID: 12, itemCode: 0, quantity: 0, actions: "Cook in 340ºC pizza oven until crust is done",isAction:true),
        RecipeStep(recipeID: 03, rowID: 13, itemCode: 22, quantity: 10, actions: ""),
        RecipeStep(recipeID: 03, rowID: 14, itemCode: 0, quantity: 0, actions: "Drizzle Huli Huli sauce over pizza",isAction:true),
        RecipeStep(recipeID: 04, rowID: 00, itemCode: 39, quantity: 260, actions: ""),
        RecipeStep(recipeID: 04, rowID: 01, itemCode: 0, quantity: 0, actions: "Warm to room temperature before service",isAction:true),
        RecipeStep(recipeID: 04, rowID: 02, itemCode: 0, quantity: 590, actions: "From one dough ball press out to 25cm",isAction:true),
        RecipeStep(recipeID: 04, rowID: 03, itemCode: 17, quantity: 1, actions: "Sliced"),
        RecipeStep(recipeID: 04, rowID: 04, itemCode: 15, quantity: 6, actions: "Whole Leaves"),
        RecipeStep(recipeID: 04, rowID: 05, itemCode: 14, quantity: 100, actions: "Sliced into medallions"),
        RecipeStep(recipeID: 04, rowID: 06, itemCode: 0, quantity: 0, actions: "Add topping in the order of tomatoes, cheese and then basil leaves.",isAction:true),
        RecipeStep(recipeID: 04, rowID: 07, itemCode: 0, quantity: 0, actions: "Cook in 340ºC pizza oven until crust is done",isAction:true),
        
        
        RecipeStep(recipeID: 05, rowID: 00, itemCode: 38, quantity: 260, actions: ""),
        RecipeStep(recipeID: 05, rowID: 01, itemCode: 0, quantity: 0, actions: "Warm to room temperature before service",isAction:true),
        RecipeStep(recipeID: 05, rowID: 02, itemCode: 0, quantity: 0, actions: "From one dough ball press out to 25cm",isAction:true),
        RecipeStep(recipeID: 05, rowID: 03, itemCode: 12, quantity: 100, actions: ""),
        RecipeStep(recipeID: 05, rowID: 04, itemCode: 0, quantity: 0, actions: "Cover pizza with sauce",isAction:true),
        RecipeStep(recipeID: 05, rowID: 05, itemCode: 12, quantity: 100, actions: ""),
        RecipeStep(recipeID: 05, rowID: 06, itemCode: 0, quantity: 0, actions: "Cover pizza with Cheese",isAction:true),
        RecipeStep(recipeID: 05, rowID: 07, itemCode: 18, quantity: 0.5, actions: "In 1/8 inch thick slices"),
        RecipeStep(recipeID: 05, rowID: 08, itemCode: 09, quantity: 75, actions: "julienne"), //pineapple
        RecipeStep(recipeID: 05, rowID: 09, itemCode: 19, quantity: 50, actions: ""),
        RecipeStep(recipeID: 05, rowID: 10, itemCode: 20, quantity: 75, actions: "Diced"),
        RecipeStep(recipeID: 05, rowID: 11, itemCode: 0, quantity: 0, actions: "Add toppings.",isAction:true),
        RecipeStep(recipeID: 05, rowID: 12, itemCode: 0, quantity: 0, actions: "Cook in 340ºC pizza oven until crust is done",isAction:true),
    ]
    }
    
    
    
    
}



